### PR TITLE
added installation instructions

### PR DESCRIPTION
**Pull request by dbeddoes**

### CODE REVIEW

**Review by k8-byte — CHANGES_REQUESTED** [review]
I think we need to expand slightly on how to download the source code - this is the part people are having problems with. Explain that they should click the code button, etc, etc. 

Also, are we still directing people to github, or do the zip on the website?

**Comment by dbeddoes** [comment]
> I think we need to expand slightly on how to download the source code - this is the part people are having problems with. Explain that they should click the code button, etc, etc.
> 
> Also, are we still directing people to github, or do the zip on the website?

I believe we are linking to the .zip on github from the website. So users will just click the link and it will start the download.

**Comment by dbeddoes** [comment]
I really need to release a version of the exe with the installer but first Kate and I need to resolve the font metric bug thing. There is a pending pull request for that (https://github.com/IrisDynamics/IrisControls_source/pull/176) but we weren't 100% happy with that.

**Review by k8-byte — APPROVED** [review]
😎

**Pull request merged**
